[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.14.0"
memoize = "0.5.1"
microlp = "0.2.11"
num = "0.4.3"
pathfinding = "4.14.0"
regex = "1.12.2"
